name: MarinaOrchestra
favicon: null
layout_spectrum: 0.5293
typography_spectrum: 0.48522
title: Marina Orchestra
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cafbff'
    - '#be6d52'
    - '#6d936a'
    - '#f8f4aa'
    - '#cbb9ab'
  brandStrength: 0.25
  lightness: 0.8700883395504206
  saturation: 0.14986031036823988
  rhythmicContrast: 0.5716639442835003
purpose: []
