name: MarinaOrchestra
favicon: null
layout_spectrum: 0.61186
typography_spectrum: 0.72903
title: Marina Orchestra
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#99b2c8'
    - '#688293'
    - '#444b55'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
