name: MarinaOrchestra
favicon: null
layout_spectrum: 0.61186
typography_spectrum: 0.72903
title: Marina Orchestra
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cafbff'
    - '#be6d52'
    - '#6d936a'
    - '#f8f4aa'
    - '#cbb9ab'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
